#NumPy:
-Numerical Python: supports multidimensional arrays over which you can easily apply mathematical operations.

In [5]:
import numpy as np

In [4]:
distance = [10,15,17,26]
time = [0.30,0.47,0.55,1.20]

np_distance = np.array(distance)
np_time = np.array(time)

speed= np_distance/ np_time
speed
type(speed)

numpy.ndarray

In [6]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [7]:
a.ndim

2

In [8]:
a.shape

(2, 2)

In [9]:
a.dtype

dtype('int32')

In [10]:
a.size

4

In [14]:
a[0][1]

2

In [11]:
states = np.array(["guj","maha","mp","up","ap"])
states

array(['guj', 'maha', 'mp', 'up', 'ap'], dtype='<U4')

In [13]:
states[2:4]

array(['mp', 'up'], dtype='<U4')

In [12]:
len(states)

5

In [15]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a[1:2,1:]

array([[5, 6]])

In [19]:
a[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [22]:
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [23]:
a+b

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [24]:
b-a

array([[ 9, 18, 27],
       [36, 45, 54],
       [63, 72, 81]])

In [25]:
a*b

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [26]:
a/b

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [27]:
a//b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [28]:
b%a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [30]:
a**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [31]:
b<50 #Comparision

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [32]:
b[b<50] #Comparision with condition

array([10, 20, 30, 40])

In [3]:
import numpy as np
marks =np.array([[45,78,67,90,84],[50,68,72,82,42]])
marks[marks<50]

array([45, 42])