In [2]:
import numpy as np

In [4]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a[(a>5)|(a==8)]

array([6, 7, 8, 9])

In [5]:
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
b[(b!=10)|(b>30)]

array([20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
for i in a:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [7]:
for i in a:
    #print(i)
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9


In [8]:
marks =np.array([[45,78,67,90,84],[50,68,72,82,42]])
marks[marks<50]

array([45, 42])

In [9]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a1=a
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a1[1][1]=50
a1

array([[ 1,  2,  3],
       [ 4, 50,  6],
       [ 7,  8,  9]])

In [12]:
a

array([[ 1,  2,  3],
       [ 4, 50,  6],
       [ 7,  8,  9]])

In [13]:
a2=a.view()
a2

array([[ 1,  2,  3],
       [ 4, 50,  6],
       [ 7,  8,  9]])

In [14]:
a2[1][1]=5
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
a3 =a.copy()
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a3[1][1]=50
a3

array([[ 1,  2,  3],
       [ 4, 50,  6],
       [ 7,  8,  9]])

In [18]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [24]:
from numpy import pi

In [25]:
np.sin(2*pi)

-2.4492935982947064e-16

In [26]:
np.cos(pi)

-1.0

In [29]:
#Floor and Ceiling:
print(np.floor(np.array([12.34,-9.45,16.23,10.02])))
np.ceil(np.array([12.34,-9.45,16.23,10.02]))

[ 12. -10.  16.  10.]


array([13., -9., 17., 11.])

In [30]:
#Expotential:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [31]:
#Log:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [32]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
a.reshape(1,9) #Makes a new array

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [34]:
a.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [35]:
a.resize(9,1) #change the original array

In [36]:
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [37]:
a.flatten() #Makes a new array with one dimension

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [39]:
a.ravel() #makes a new array with one dimension

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a.resize(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr=np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9]])
arr

<ipython-input-4-9162179c0c35>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr=np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9]])


array([list([1, 2, 3, 4, 5, 6]), list([7, 8, 9])], dtype=object)

In [5]:
np.split(arr,2)

[array([list([1, 2, 3, 4, 5, 6])], dtype=object),
 array([list([7, 8, 9])], dtype=object)]

In [51]:
#Broadcasting:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [53]:
#Transpose: alter rows and columns 
arr.T

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
#Trace : diagonal elements sum - need multi dimensional array
np.trace(a)

15

In [55]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
a2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])