In [4]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.diag(a)  #K= diagonal - by default its always 0

array([1, 5, 9])

In [6]:
np.diag(a,k=1)

array([2, 6])

In [7]:
np.diag(a,k=2)

array([3])

In [8]:
np.diag(a,k=-1)

array([4, 8])

In [9]:
np.diag(a,k=-2)

array([7])

In [10]:
np.tri(5,5) # Tri= triangle - by default 1 and 0 (From 0 to negetaive - 1 and from 1 to positive =0)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.tri(5,5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.]])

In [12]:
np.tri(5,5,k=2)

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.tril(a) # Tril = lower triangle

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [15]:
np.tril(a,k=1)

array([[1, 2, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.tril(a,k=-1)

array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

In [17]:
np.triu(a) #Triu = uper triangle

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [18]:
np.triu(a,k=1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

In [19]:
np.triu(a,k=-1)

array([[1, 2, 3],
       [4, 5, 6],
       [0, 8, 9]])

In [20]:
np.diagflat(a) # diagflat = bring all elements to diagonal nd rest zero to form array.

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [21]:
b= np.array([1,2,3])
b

array([1, 2, 3])

In [22]:
np.diagflat(b) 

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [23]:
print(range(8))

range(0, 8)


In [25]:
list(range(8))

[0, 1, 2, 3, 4, 5, 6, 7]

In [26]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [27]:
np.arange(0.2,7.8,0.33)

array([0.2 , 0.53, 0.86, 1.19, 1.52, 1.85, 2.18, 2.51, 2.84, 3.17, 3.5 ,
       3.83, 4.16, 4.49, 4.82, 5.15, 5.48, 5.81, 6.14, 6.47, 6.8 , 7.13,
       7.46, 7.79])

In [ ]:
difference between range and arange:
    - built in function , method of array
    - provides only range, provide array
    - integers only, integers and floats

In [28]:
 np.linspace(10,20,10)   # gives elements with evenly adding the values.

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [29]:
np.linspace(5,30,10)

array([ 5.        ,  7.77777778, 10.55555556, 13.33333333, 16.11111111,
       18.88888889, 21.66666667, 24.44444444, 27.22222222, 30.        ])

In [30]:
np.logspace(10,20,10) #gives elements with evenly adding the log values.

array([1.00000000e+10, 1.29154967e+11, 1.66810054e+12, 2.15443469e+13,
       2.78255940e+14, 3.59381366e+15, 4.64158883e+16, 5.99484250e+17,
       7.74263683e+18, 1.00000000e+20])

In [31]:
from numpy import random as rd

In [33]:
rd.rand(3,5) # gives array in between zero to one value as per the shape given.

array([[0.99908318, 0.45354346, 0.31520241, 0.97082425, 0.59258346],
       [0.87166719, 0.52964155, 0.55033374, 0.44908633, 0.73996659],
       [0.39730334, 0.86434078, 0.03259886, 0.64987564, 0.28696334]])

In [34]:
rd.randn(2,2)  # gives array in normal distribution as per the given shape.

array([[ 1.17620549, -1.37691643],
       [-1.21162102, -1.68236011]])

In [35]:
rd.randint(5,30,20) #gives array of integers randomly as per given value with given dimension

array([28, 29, 16, 23, 18, 29, 22, 29, 20,  5, 27,  7,  8, 20, 21, 10, 17,
       20, 10, 26])

In [36]:
a= rd.randint(5,30,(3,3))

In [37]:
a

array([[ 8, 12, 14],
       [ 8, 26, 23],
       [24, 15, 18]])

In [38]:
a.max()

26

In [39]:
a.min()

8

In [40]:
a.mean()

16.444444444444443

In [42]:
np.median(a)

15.0

In [43]:
np.std(a)

6.361535648133172

In [45]:
np.var(a)

40.46913580246914